src/main/default/objects/Environment__mdt/Environment__mdt.object-meta.xml
<CustomObject>
    <description>Maps the API name to a specific sandbox name. 'Prod' and 'Scratch' are constants, and will always point to production org and all scratch orgs respectively</description>
    <label>Environment</label>
    <pluralLabel>Environments</pluralLabel>
</CustomObject>

src/main/default/objects/Feature__mdt/Feature__mdt.object-meta.xml
<CustomObject>
    <description>An abstraction of an Apex feature that you want to turn on/off in different environments</description>
    <label>Feature</label>
    <pluralLabel>Features</pluralLabel>
</CustomObject>

src/main/default/objects/Feature__mdt/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <description>The environment in which this feature is enabled or disabled</description>
    <inlineHelpText>The environment in which this feature is enabled or disabled</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__mdt</referenceTo>
    <relationshipLabel>Features</relationshipLabel>
    <relationshipName>Features</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

src/main/default/objects/Feature__mdt/fields/Is_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Is_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>FeatureEnabled</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/classes/FeatureToggle.cls
public class FeatureToggle {

    static Environment__mdt runtimeEnv;
    static Map<String, Map<String, Boolean>> featureCache = new Map<String, Map<String, Boolean>>(); 

    public class FeatureNotFoundException extends Exception {}
    public class EnvironmentNotFoundException extends Exception {}

    private static Boolean isEnabled(String featureName, Environment__mdt env) {

        if (featureCache.get(env.Label).containsKey(featureName)) {
            return featureCache.get(env.Label).get(featureName);
        }

        try {
            Feature__mdt feature = getFeature(featureName, env);
        } catch (FeatureNotFoundException e) {
            return false;
        }

        featureCache.get(env.Label).put(featureName, feature.Is_Enabled__c);
        return feature.Is_Enabled__c;
    }

    public static Boolean isEnabled(String featureName, String environment) {
        return isEnabled(featureName, getEnvironment(environment));
    }
    
    public static Boolean isEnabled(String featureName) {
        return isEnabled(featureName, getRuntimeEnvironment());
    }

    public static Feature__mdt getFeature(String featureName) {
        return getFeature(featureName, getRuntimeEnvironment());
    }

    public static Feature__mdt getFeature(String featureName, String environment) {
        return getFeature(featureName, getEnvironment(environment));
    }

    public static Feature__mdt getFeature(String featureName, Environment__mdt env) {
        if (String.isBlank(featureName)) {
            throw new IllegalArgumentException('Feature cannot be blank');
        }

        if (env == null) {
            throw new EnvironmentNotFoundException('Environment ' + env.Label + ' not found');
        }

        Feature__mdt feature  = [SELECT Is_Enabled__c FROM Feature__mdt WHERE Label = :featureName AND Environment__c = :env.Id LIMIT 1];

        if (feature == null) {
            throw new FeatureNotFoundException('Feature ' + featureName + ' not found in environment ' + env);
        }

        return feature;
    }

    private static Environment__mdt getEnvironment(String environment) {
        if (String.isBlank(environment)) {
            throw new IllegalArgumentException('Environment cannot be blank');
        }

        if (String.containsWhitespace(environment)) {
            throw new IllegalArgumentException('Environment cannot contain white spaces');
        }

        Environment__mdt env = Environment__mdt.getInstance(env);
        if (env == null) {
            throw new EnvironmentNotFoundException('Environment ' + environment + ' not found');
        }
        return env;
    }

    private static Environment__mdt getRuntimeEnvironment() {

        if (runtimeEnv != null) {
            return runtimeEnv;
        }

        // checks if in production
        Organization org = [SELECT isSandbox FROM Organization LIMIT 1];
        if (!org.isSandbox) {
            setEnvironment(getEnvironment('Prod'));
            return runtimeEnv;
        }

        // check if in sandbox or scratch org
        System.URL domainURL = System.URL.getOrgDomainUrl();
        String hostName = domainURL.getHost();
        System.Domain currentDomain = System.DomainParser.parse(hostName);

        String sandboxName = currentDomain.getSandboxName(); // returns the name of the sandbox, or null if not in a sandbox (as i have checked for production above, null means scratch org)

        if (sandboxName == null) {
            setEnvironment(getEnvironment('Scratch'));
        } else {
            setEnvironment(getEnvironment(sandboxName));
        }
        
        return runtimeEnv;
    }

    @TestVisible
    private static void setEnvironment(Environment__mdt env) {
        runtimeEnv = env;
    }

}