src/main/default/objects/Environment__mdt/Environment__mdt.object-meta.xml
<CustomObject>
    <description>Maps the API name to a specific sandbox name. 'Prod' and 'Scratch' are constants, and will always point to production org and all scratch orgs respectively</description>
    <label>Environment</label>
    <pluralLabel>Environments</pluralLabel>
</CustomObject>

src/main/default/objects/Feature__mdt/Feature__mdt.object-meta.xml
<CustomObject>
    <description>An abstraction of an Apex feature that you want to turn on/off in different environments</description>
    <label>Feature</label>
    <pluralLabel>Features</pluralLabel>
</CustomObject>

src/main/default/objects/Feature__mdt/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>FeatureEnabled</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Feature__mdt/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <description>The environment in which this feature is enabled or disabled</description>
    <inlineHelpText>The environment in which this feature is enabled or disabled</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__mdt</referenceTo>
    <relationshipLabel>Features</relationshipLabel>
    <relationshipName>Features</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

src/main/default/objects/Feature__mdt/fields/SharedFeatureName__c.field-meta.xml
<CustomField>
    <fullName>SharedFeatureName__c</fullName>
    <description>The &quot;True&quot; name of the feature. Which will be the same for multiple feature records with different environments</description>
    <inlineHelpText>The &quot;True&quot; name of the feature. Which will be the same for multiple features records with different environments</inlineHelpText>
    <label>SharedFeatureName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/FeatureManager.cls
public with sharing class FeatureManager {
    
    public static Boolean isEnabled(String featureName) {
        // logic for getting metadata with the same name as featureName, and in the same environment as the current one
        Environment__mdt currentEnvironment;

        try{
            currentEnvironment = getCurrentEnvironment();
        }
        catch(Exception e){
            System.debug('Error getting current environment: ' + e.getMessage() + '. stack trace: ' + e.getStackTraceString());
            return false;
        }


        Feature__mdt feature;

        try {
            feature = [SELECT Enabled__c FROM Feature__mdt WHERE SharedFeatureName__c = :featureName AND Environment__c = :currentEnvironment.Id LIMIT 1];
        }
        catch (Exception e) {
            System.debug('Feature not found: ' + featureName + '. message: ' + e.getMessage() + '. stack trace: ' + e.getStackTraceString());
            return false;
        }

        return feature.Enabled__c;
    }
    


    private static Environment__mdt getCurrentEnvironment() {

        // checks if in production
        Organization org = [SELECT isSandbox FROM Organization LIMIT 1];
        if(!org.isSandbox){ // isSandbox is true for both sandbox and scratch orgs, so if false it is production
            Environment__mdt env = [SELECT Id, DeveloperName FROM Environment__mdt WHERE DeveloperName = 'Prod' LIMIT 1];
            return env;
        }

        // check if in sandbox or scratch org
        System.URL domainURL = System.URL.getOrgDomainUrl();
        String hostName = domainURL.getHost();
        System.Domain currentDomain = System.DomainParser.parse(hostName);

        String sandboxName = currentDomain.getSandboxName(); // returns the name of the sandbox, or null if not in a sandbox (as i have checked for production above, null means scratch org)


        if(sandboxName == null){
            Environment__mdt env = [SELECT Id, DeveloperName FROM Environment__mdt WHERE DeveloperName = 'Scratch' LIMIT 1];
            return env;
        }
        else{
            Environment__mdt env = [SELECT Id, DeveloperName FROM Environment__mdt WHERE DeveloperName = :sandboxName LIMIT 1];
            return env;
        }
    }
}










// Feature__mdt feature;

// try {
//     feature = [SELECT Enabled__c FROM Feature__mdt WHERE DeveloperName = :featureName LIMIT 1];
// }
// catch (Exception e) {
//     System.debug('Feature not found: ' + featureName + '. message: ' + e.getMessage() + '. stack trace: ' + e.getStackTraceString());
//     return false;
// }

// return feature.Enabled__c;